# Generated by Django 5.0.6 on 2024-06-26 07:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MileStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('required_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 6, 26, 12, 31, 24, 683925))),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('performance_threshold', models.IntegerField(default=0)),
                ('gain_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 6, 26, 12, 31, 24, 682135))),
            ],
        ),
        migrations.CreateModel(
            name='MileStoneAssignToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 6, 26, 12, 31, 24, 684248))),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone', to='quizapp.milestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 6, 26, 12, 31, 24, 683550))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_user', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_quiz', to='quizapp.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQusetions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('option_1', models.CharField(max_length=100)),
                ('option_2', models.CharField(max_length=100)),
                ('option_3', models.CharField(max_length=100)),
                ('option_4', models.CharField(max_length=100)),
                ('right_option', models.CharField(choices=[('option_1', 'option_1'), ('option_2', 'option_2'), ('option_3', 'option_3'), ('option_4', 'option_4')], max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 6, 26, 12, 31, 24, 682648))),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='quizapp.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 6, 26, 12, 31, 24, 683109))),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_quiz', to='quizapp.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
