# Generated by Django 5.0.6 on 2024-06-26 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 17, 30, 55, 529155)),
        ),
        migrations.AlterField(
            model_name='point',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 17, 30, 55, 528785)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 17, 30, 55, 527430)),
        ),
        migrations.AlterField(
            model_name='quizqusetions',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 17, 30, 55, 527928)),
        ),
        migrations.AlterField(
            model_name='result',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 17, 30, 55, 528381)),
        ),
        migrations.DeleteModel(
            name='MileStoneAssignToUser',
        ),
    ]
