# Generated by Django 5.0.6 on 2024-06-26 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_alter_milestone_created_at_alter_point_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='quiz',
        ),
        migrations.AlterField(
            model_name='milestone',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 23, 23, 10, 59583)),
        ),
        migrations.AlterField(
            model_name='point',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 23, 23, 10, 59034)),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 23, 23, 10, 56932)),
        ),
        migrations.AlterField(
            model_name='quizqusetions',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 23, 23, 10, 57684)),
        ),
        migrations.AlterField(
            model_name='result',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 26, 23, 23, 10, 58322)),
        ),
    ]
